version: "3.9"

services:
  django:
    build: .
    image: lodi-interview-backend
    env_file:
      - ./.env
    ports:
      - 8000
    entrypoint: ./entrypoint_django.sh

    labels:
      traefik.enable: "true"

      traefik.http.routers.lodi-interview.rule: Host(`qstnr.intvw.logodiffusion.com`)
      traefik.http.routers.lodi-interview.entrypoints: web,websecure
      traefik.http.routers.lodi-interview.tls: "true"
      traefik.http.routers.lodi-interview.tls.certresolver: production

networks:
  default:
    name: "traefik"
    external: true
