# Generated by Django 4.2.3 on 2023-07-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.EmailField(max_length=254)),
                ('occupation', models.TextField()),
                ('discovery', models.TextField()),
                ('usageExplanation', models.TextField()),
            ],
        ),
    ]
